swagger: '2.0'
info:
  title: Conformal Prediction Log D 
  description: >-
    This is a Conformal Prediction Service for predicting Log D values for compounds. The 
    underlying model has been trained and evaluated on ChEMBL 23 data. Modeling is done using
    CPSign, product of GenettaSoft AB.
  version: 0.0.1
  contact:
    name: CPSign Support
    url: 'http://cpsign-docs.genettasoft.com'
    email: info@genettasoft.com
basePath: /v1
schemes:
  - http
produces:
  - application/json
consumes:
  - multipart/form-data
paths:


  /logd:
    get:
      tags: 
        - Predict
      produces:
        - application/json
      summary: Predict a single compound in SMILES format
      parameters:
        - $ref: "#/parameters/smiles"
        - name: confidence
          in: query
          description: The desired confidence of the prediction
          required: false
          type: number
          format: double
          minimum: 0.0
          maximum: 1.0
          default: 0.8
      responses:
        '200':
          description: prediction result
          schema:
            $ref: "#/definitions/Prediction"
        '400':
          description: SMILES not possible to parse
          schema:
            $ref: "#/definitions/Error"
        '500':
          description: Server error
          schema:
            $ref: "#/definitions/Error"
    post:
      tags: 
        - Predict
      produces:
        - application/json
      summary: Predict the result from a complete file, either in SDF or SMILES (one SMILES per line)
      description: >-
        Predict the result from a complete file, either in SDF or SMILES (one SMILES per line).
        <b>Either</b> upload the datafile <b>or</b> send a URI where the dataset can be read from (must be a publically
        accessible URI). The file will be predicted and new properties will be added to the properties already present
        in the file. The result from this endpoint is the URI of a <b>Task</b> that should be queried for when the 
        prediction has finished.
      parameters:
        - name: uri
          in: query
          description: A dataset to be predicted
          required: false
          type: string
          format: uri
        - name: dataFile
          in: formData
          type: file
          required: false
          description: A dataset to be predicted
        - name: confidence
          in: query
          description: The desired confidence of the prediction
          required: false
          type: number
          format: double
          minimum: 0.0
          maximum: 1.0
          default: 0.8
      responses:
        '302':
          description: Prediction accepted by server - redirect to prediction task to query
        '400':
          description: Bad request (missing dataset)
          schema:
            $ref: "#/definitions/Error"
        '500':
          description: Server error
          schema:
            $ref: "#/definitions/Error"



  /tasks:
    get:
      tags:
        - Task
      summary: Get a list of all available tasks URIs
      description: Get a list of all available tasks URIs
      responses:
        '200':
          description: list of running tasks
          schema:
            type: array
            items:
              type: string
              description: URI of running tasks
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/Error'
  '/tasks/{id}':
    get:
      tags:
        - Task
      summary: Get status of a specific task
      description: Get status of a specific task
      parameters:
        - name: id
          in: path
          description: The Task URI to query
          type: string
          required: true
      responses:
        '301':
          description: Prediction has successfully finished
          schema:
            type: string
            format: uri
            description: URI of the result from this Task
        '202':
          description: Task is running
          schema:
            $ref: "#/definitions/TaskInfo"
        '404':
          description: Task for id not found
          schema:
            $ref: '#/definitions/Error'
        '502':
          description: Task has failed
          schema:
            $ref: '#/definitions/Error'


definitions:
  Error:
    type: object
    description: Error
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
        description: HTTP status code
        minimum: 100
        maximum: 600
      message:
        type: string
        description: Error message
  smiles:
    type: string
    description: Compound structure notated using SMILES notation
    x-ontology: http://edamontology.org/format_1196
  Prediction:
    type: object
    description: Prediction result
    properties:
      smiles:
        $ref: "#/definitions/smiles"
      lower:
        type: number
        format: double
        description: The lower range of the prediction value
      upper:
        type: number
        format: double
        description: The upper range of the prediction value
      predictionMidpoint:
        type: number
        format: double
        description: >-
          The predicted midpoint value, note that this is the 
          prediction given by the underlying SVM-models and 
          there is NO confidence assigned to this point value!
  TaskInfo:
    type: object
    description: Information about a running Task
    properties:
      uri:
        type: string
        format: uri
        description: The URI of the Task
      progress:
        type: number
        minimum: 0
        maximum: 100
        description: Progress [0-100%]
      currentRuntime:
        type: number
        description: How long the task has been running (milliseconds)


parameters:
  smiles:
    name: smiles
    in: query
    required: true
    description: Compound structure notation using SMILES notation
    type: string
    x-ontology: http://edamontology.org/format_1196
